#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:12.20.1

pipelines:
  default:
        - step:
            name: Build
            caches:
              - node
            script:
              - npm install
              - npm run build
            artifacts:
              - dist/**